branches:
  only:
      - /.*/

matrix:
  fast_finish: true
  include:
    - language: java
      jdk: openjdk8
      os: linux
      dist: xenial
      sudo: required

    - language: java
      jdk: openjdk9
      os: linux
      dist: xenial
      sudo: required

    - language: java
      jdk: openjdk10
      os: linux
      dist: xenial
      sudo: required

    - language: java
      jdk: openjdk11
      os: linux
      dist: xenial
      sudo: required

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - gradle wrapper
script: 
  - chmod +x gradlew
  - gradlew test bootJar
